/**
 * Sample species data for development and offline fallback
 * In production, this would come from OBIS API
 */

import { OBISSpecies } from './obis-client';

export const sampleSpecies: OBISSpecies[] = [
  {
    id: 1,
    scientificName: 'Tursiops truncatus',
    vernacularName: 'Bottlenose Dolphin',
    kingdom: 'Animalia',
    phylum: 'Chordata',
    class: 'Mammalia',
    order: 'Cetacea',
    family: 'Delphinidae',
    genus: 'Tursiops',
    species: 'truncatus',
    taxonRank: 'Species',
    records: 15420,
  },
  {
    id: 2,
    scientificName: 'Caretta caretta',
    vernacularName: 'Loggerhead Sea Turtle',
    kingdom: 'Animalia',
    phylum: 'Chordata',
    class: 'Reptilia',
    order: 'Testudines',
    family: 'Cheloniidae',
    genus: 'Caretta',
    species: 'caretta',
    taxonRank: 'Species',
    records: 8932,
  },
  {
    id: 3,
    scientificName: 'Chelonia mydas',
    vernacularName: 'Green Sea Turtle',
    kingdom: 'Animalia',
    phylum: 'Chordata',
    class: 'Reptilia',
    order: 'Testudines',
    family: 'Cheloniidae',
    genus: 'Chelonia',
    species: 'mydas',
    taxonRank: 'Species',
    records: 12456,
  },
  {
    id: 4,
    scientificName: 'Carcharodon carcharias',
    vernacularName: 'Great White Shark',
    kingdom: 'Animalia',
    phylum: 'Chordata',
    class: 'Elasmobranchii',
    order: 'Lamniformes',
    family: 'Lamnidae',
    genus: 'Carcharodon',
    species: 'carcharias',
    taxonRank: 'Species',
    records: 3421,
  },
  {
    id: 5,
    scientificName: 'Mobula birostris',
    vernacularName: 'Giant Manta Ray',
    kingdom: 'Animalia',
    phylum: 'Chordata',
    class: 'Elasmobranchii',
    order: 'Myliobatiformes',
    family: 'Mobulidae',
    genus: 'Mobula',
    species: 'birostris',
    taxonRank: 'Species',
    records: 2156,
  },
  {
    id: 6,
    scientificName: 'Amphiprion ocellaris',
    vernacularName: 'Clownfish',
    kingdom: 'Animalia',
    phylum: 'Chordata',
    class: 'Actinopterygii',
    order: 'Perciformes',
    family: 'Pomacentridae',
    genus: 'Amphiprion',
    species: 'ocellaris',
    taxonRank: 'Species',
    records: 5678,
  },
  {
    id: 7,
    scientificName: 'Acropora cervicornis',
    vernacularName: 'Staghorn Coral',
    kingdom: 'Animalia',
    phylum: 'Cnidaria',
    class: 'Anthozoa',
    order: 'Scleractinia',
    family: 'Acroporidae',
    genus: 'Acropora',
    species: 'cervicornis',
    taxonRank: 'Species',
    records: 4231,
  },
  {
    id: 8,
    scientificName: 'Octopus vulgaris',
    vernacularName: 'Common Octopus',
    kingdom: 'Animalia',
    phylum: 'Mollusca',
    class: 'Cephalopoda',
    order: 'Octopoda',
    family: 'Octopodidae',
    genus: 'Octopus',
    species: 'vulgaris',
    taxonRank: 'Species',
    records: 7845,
  },
  {
    id: 9,
    scientificName: 'Megaptera novaeangliae',
    vernacularName: 'Humpback Whale',
    kingdom: 'Animalia',
    phylum: 'Chordata',
    class: 'Mammalia',
    order: 'Cetacea',
    family: 'Balaenopteridae',
    genus: 'Megaptera',
    species: 'novaeangliae',
    taxonRank: 'Species',
    records: 9234,
  },
  {
    id: 10,
    scientificName: 'Hippocampus reidi',
    vernacularName: 'Longsnout Seahorse',
    kingdom: 'Animalia',
    phylum: 'Chordata',
    class: 'Actinopterygii',
    order: 'Syngnathiformes',
    family: 'Syngnathidae',
    genus: 'Hippocampus',
    species: 'reidi',
    taxonRank: 'Species',
    records: 1876,
  },
  {
    id: 11,
    scientificName: 'Lutjanus campechanus',
    vernacularName: 'Red Snapper',
    kingdom: 'Animalia',
    phylum: 'Chordata',
    class: 'Actinopterygii',
    order: 'Perciformes',
    family: 'Lutjanidae',
    genus: 'Lutjanus',
    species: 'campechanus',
    taxonRank: 'Species',
    records: 6543,
  },
  {
    id: 12,
    scientificName: 'Sphyrna mokarran',
    vernacularName: 'Great Hammerhead Shark',
    kingdom: 'Animalia',
    phylum: 'Chordata',
    class: 'Elasmobranchii',
    order: 'Carcharhiniformes',
    family: 'Sphyrnidae',
    genus: 'Sphyrna',
    species: 'mokarran',
    taxonRank: 'Species',
    records: 1234,
  },
  {
    id: 13,
    scientificName: 'Physeter macrocephalus',
    vernacularName: 'Sperm Whale',
    kingdom: 'Animalia',
    phylum: 'Chordata',
    class: 'Mammalia',
    order: 'Cetacea',
    family: 'Physeteridae',
    genus: 'Physeter',
    species: 'macrocephalus',
    taxonRank: 'Species',
    records: 5432,
  },
  {
    id: 14,
    scientificName: 'Eretmochelys imbricata',
    vernacularName: 'Hawksbill Sea Turtle',
    kingdom: 'Animalia',
    phylum: 'Chordata',
    class: 'Reptilia',
    order: 'Testudines',
    family: 'Cheloniidae',
    genus: 'Eretmochelys',
    species: 'imbricata',
    taxonRank: 'Species',
    records: 3765,
  },
  {
    id: 15,
    scientificName: 'Thunnus albacares',
    vernacularName: 'Yellowfin Tuna',
    kingdom: 'Animalia',
    phylum: 'Chordata',
    class: 'Actinopterygii',
    order: 'Perciformes',
    family: 'Scombridae',
    genus: 'Thunnus',
    species: 'albacares',
    taxonRank: 'Species',
    records: 8921,
  },
];

/**
 * Get random species for an MPA (development fallback)
 */
export function getRandomSpeciesForMPA(count: number = 10): OBISSpecies[] {
  const shuffled = [...sampleSpecies].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, sampleSpecies.length));
}
